Repository Lercerss/graphelier, pull requests merged in 2019-10, with the labels that each got.

#57 [#26] Added ui tests for date and time picker
  app/src/components/OrderBookSnapshot.js
  app/src/tests/component-tests/OrderBookSnapshot.test.js
  app/src/tests/utils/mock-data.js
Labels: setup

#61 [#55] Added golangci config
  .circleci/config.yml
  .golangci.yml
  README.md
  app/README.md
  core/Dockerfile
  core/README.md
Labels: setup

#64 [#29] Relative box sizes for quantities
  app/src/components/Order.js
  app/src/components/PriceLevel.js
  app/src/components/TimestampOrderBookScroller.js
  app/src/styles/Order.js
  app/src/styles/OrderBookSnapshot.js
  app/src/styles/PriceLevel.js
Labels: fixed time display, front-end, task

#60 [#59] removed inefficient slider callbacks/setStates
  app/src/components/OrderBookSnapshot.js
  app/src/components/TimestampOrderBookScroller.js
Labels: bug

#67 [#41] implemented orderbook logic to build orderbook with applied messages
  core/.gitignore
  core/README.md
  core/graphelier-service/api/hndlrs/obhandler.go
  core/graphelier-service/api/hndlrs/orderbook.go
  core/graphelier-service/api/models/orderbook.go
  core/graphelier-service/db/mongo.go
  core/graphelier-service/models/messages.go
  core/graphelier-service/models/orderbooks.go
  docker-compose.yml
Labels: time-dimension

#58 #40 +. Using FE template for graphelier tool. UI tweaks, and small code changes.
  .gitignore
  .vs/graphelier/v16/.suo
  app/package-lock.json
  app/package.json
  app/src/App.js
  app/src/components/Order.js
  app/src/components/OrderBookSnapshot.js
  app/src/components/PriceLevel.js
  app/src/components/TimestampOrderBookScroller.js
  app/src/components/template/Dashboard.js
  app/src/components/template/listItems.js
  app/src/constants/Constants.js
  app/src/services/OrderBookService.js
  app/src/styles/Dashboard.js
  app/src/styles/OrderBookSnapshot.js
  app/src/styles/PriceLevel.js
  app/src/styles/TimestampOrderBookScroller.js
Labels: fixed time display

#56 [#25, #34] Extending sample to full days
  core/scripts/Dockerfile
  core/scripts/importer.py
  core/scripts/lobster/__init__.py
  core/scripts/lobster/extender.py
  core/scripts/lobster/parser.py
  core/scripts/models/message.py
  core/scripts/models/order_book.py
  core/scripts/pylintrc
  core/scripts/tests/messages_sample.fixture
  core/scripts/tests/test_extender.py
  core/scripts/tests/test_orderbook.py
Labels: data

#69 [#55] Cache dependencies in CI
  .circleci/config.yml
  .gitignore
  .vs/graphelier/v16/.suo
  app/src/App.js
  app/src/components/OrderBookSnapshot.js
  app/src/components/TimestampOrderBookScroller.js
  app/src/components/template/Dashboard.js
  app/src/store/index.js
  app/src/styles/Dashboard.js
  app/src/styles/OrderBookSnapshot.js
  docker-compose.yml
Labels: setup

#72 [#40] Added more styling to the Slider and the Card
  app/src/App.js
  app/src/components/OrderBookSnapshot.js
  app/src/components/TimestampOrderBookScroller.js
  app/src/styles/App.js
  app/src/styles/OrderBookSnapshot.js
  app/src/styles/TimestampOrderBookScroller.js
Labels: front-end

#79 [#76] SOD offset now saved in DB
  core/db/db_setup.js
  core/scripts/importer.py
  core/scripts/models/message.py
  core/scripts/models/order_book.py
  core/scripts/mongo_db/db_utils.py
Labels: data
