Repository Lercerss/graphelier, pull requests merged in 2019-11, with the labels that each got.

#82 [#76] SOD offset now includes the dates timestamp
  core/db/db_setup.js
  core/graphelier-service/models/messages.go
  core/graphelier-service/models/orderbooks.go
  core/scripts/importer.py
Labels: data

#80 [#65] Timestamp gets converted to UTC
  app/.eslintrc.json
  app/package-lock.json
  app/package.json
  app/src/components/Order.js
  app/src/components/OrderBookSnapshot.js
  app/src/components/template/Dashboard.js
  app/src/utils/date-utils.js
  core/graphelier-service/api/hndlrs/obhandler.go
Labels: bug

#83 [#51] Serving messages with pagination
  .circleci/config.yml
  core/graphelier-service/api/hndlrs/handlers.go
  core/graphelier-service/api/hndlrs/msghandler.go
  core/graphelier-service/api/hndlrs/msghandler_test.go
  core/graphelier-service/api/hndlrs/obhandler.go
  core/graphelier-service/api/routes.go
  core/graphelier-service/db/mongo.go
  core/graphelier-service/models/messages.go
  core/graphelier-service/models/paginator.go
Labels: message-list

#84 Front-end bug fixes and ESLint setup
  app/.eslintrc.json
  app/package-lock.json
  app/package.json
  app/src/App.js
  app/src/actions/actions.js
  app/src/actions/types.js
  app/src/components/MultiDirectionalScroll.js
  app/src/components/Order.js
  app/src/components/OrderBookSnapshot.js
  app/src/components/PriceLevel.js
  app/src/components/TimestampOrderBookScroller.js
  app/src/components/WelcomeCard.js
  app/src/components/template/Dashboard.js
  app/src/components/template/listItems.js
  app/src/env/serviceWorker.js
  app/src/index.js
  app/src/reducers/reducers.js
  app/src/services/HttpClient.js
  app/src/services/OrderBookService.js
  app/src/setupTests.js
  app/src/store/index.js
  app/src/styles/App.js
  app/src/styles/Dashboard.js
  app/src/styles/MultiDirectionalScroll.js
  app/src/styles/Order.js
  app/src/styles/OrderBookSnapshot.js
  app/src/styles/PriceLevel.js
  app/src/styles/TimestampOrderBookScroller.js
  app/src/styles/WelcomeCard.js
  app/src/tests/App.test.js
  app/src/tests/component-tests/MultiDirectionalScroll.test.js
  app/src/tests/component-tests/OrderBookSnapshot.test.js
  app/src/tests/component-tests/TimestampOrderBookScroller.test.js
  app/src/tests/utils/mock-data.js
  app/src/utils/date-utils.js
  app/src/utils/number-utils.js
  app/src/utils/order-book-utils.js
Labels: fixed time display, front-end, refactor

#88 [#87] Fixed support for running app in windows with eslint
  app/.env
  app/package.json
Labels: bug

#70 Message stepping frontend
  app/src/components/OrderBookSnapshot.js
  app/src/components/TimestampOrderBookScroller.js
  app/src/constants/Constants.js
  app/src/services/OrderBookService.js
  app/src/styles/OrderBookSnapshot.js
  app/src/styles/TimestampOrderBookScroller.js
  app/src/tests/component-tests/OrderBookSnapshot.test.js
  app/src/tests/component-tests/TimestampOrderBookScroller.test.js
  app/src/tests/utils/mock-data.js
  app/src/utils/date-utils.js
  app/src/utils/order-book-utils.js
Labels: front-end, task, time-dimension

#92 [#41][#89] Fixed bug causing pricelevel duplicates
  core/graphelier-service/api/hndlrs/msghandler_test.go
  core/graphelier-service/models/messages.go
  core/graphelier-service/models/orderbooks.go
  core/graphelier-service/models/orderbooks_test.go
Labels: bug, test

#90 [#81] Adjust price on extended samples
  core/scripts/importer.py
  core/scripts/lobster/extender.py
  core/scripts/lobster/parser.py
  core/scripts/models/message.py
  core/scripts/models/order_book.py
  core/scripts/mongo_db/db_utils.py
  core/scripts/pylintrc
  core/scripts/tests/test_extender.py
  core/scripts/tests/test_orderbook.py
Labels: bug, data

#93 [#81, #90] Fixed crash when providing `-t`
  core/scripts/importer.py
Labels: bug, data

#100 [#97] Default values for initial orderbook snap
  core/scripts/importer.py
Labels: bug, data

#99 [#98] Prevent exit on error in service
  core/graphelier-service/api/hndlrs/handlers.go
Labels: bug

#85 [#35] serve orderbook deltas based on message offset
  .golangci.yml
  core/README.md
  core/graphelier-service/api/hndlrs/msghandler.go
  core/graphelier-service/api/hndlrs/msghandler_test.go
  core/graphelier-service/api/hndlrs/obhandler.go
  core/graphelier-service/api/hndlrs/obhandler_test.go
  core/graphelier-service/api/routes.go
  core/graphelier-service/db/mongo.go
  core/graphelier-service/models/messages.go
  core/graphelier-service/models/orderbooks.go
  core/graphelier-service/models/orderbooks_test.go
  core/graphelier-service/utils/utils.go
Labels: time-dimension

#101 [#35] increment bug fix
  core/graphelier-service/models/orderbooks.go
  core/graphelier-service/models/orderbooks_test.go
Labels: bug, time-dimension

#102 [#95] Converted timestamp to int to keep precision
  core/scripts/importer.py
  core/scripts/lobster/extender.py
  core/scripts/lobster/parser.py
Labels: bug, data

#103 Message List #54
  CourseAdmin/GraphelierMilestone1Document.pdf
  README.md
  app/package-lock.json
  app/src/components/MessageList.js
  app/src/components/OrderBookSnapshot.js
  app/src/components/TimestampOrderBookScroller.js
  app/src/constants/Constants.js
  app/src/constants/Enums.js
  app/src/services/OrderBookService.js
  app/src/styles/App.js
  app/src/styles/MessageList.js
  app/src/styles/OrderBookSnapshot.js
  app/src/styles/TimestampOrderBookScroller.js
  app/src/tests/component-tests/MessageList.test.js
  app/src/tests/utils/mock-data.js
  app/src/utils/date-utils.js
  app/src/utils/order-book-utils.js
  core/graphelier-service/api/hndlrs/msghandler.go
  core/graphelier-service/api/hndlrs/msghandler_test.go
  core/graphelier-service/api/hndlrs/obhandler.go
  core/graphelier-service/api/hndlrs/obhandler_test.go
  core/graphelier-service/models/orderbooks.go
  core/graphelier-service/models/orderbooks_test.go
Labels: message-list

#121 [#113] Instruments route
  core/graphelier-service/api/hndlrs/insthandler.go
  core/graphelier-service/api/hndlrs/insthandler_test.go
  core/graphelier-service/api/hndlrs/msghandler_test.go
  core/graphelier-service/api/hndlrs/obhandler_test.go
  core/graphelier-service/api/routes.go
  core/graphelier-service/db/mongo.go
Labels: instruments

#120 [#116] Remove messages without an existing order
  core/scripts/lobster/extender.py
  core/scripts/models/order_book.py
  core/scripts/tests/messages_sample.fixture
  core/scripts/tests/test_extender.py
Labels: bug, data

#119 [#117] Always send message to orderbook
  core/graphelier-service/models/orderbooks.go
Labels: bug, time-dimension

#115 Scale application display size #105
  app/package-lock.json
  app/src/components/Order.js
  app/src/styles/MessageList.js
  app/src/styles/OrderBookSnapshot.js
  app/src/styles/TimestampOrderBookScroller.js
Labels: fixed time display, message-list, story

#130 message click/#127
  app/src/components/MessageList.js
  app/src/components/OrderBookSnapshot.js
  app/src/components/TimestampOrderBookScroller.js
  app/src/components/template/Dashboard.js
  app/src/constants/Constants.js
  app/src/services/OrderBookService.js
  app/src/styles/MessageList.js
  core/.gitignore
Labels: message-list, story
