Repository Lercerss/graphelier, pull requests merged in 2020-01, with the labels that each got.

#129 [#94, #128] Store interval value in meta collection
  core/graphelier-service/api/hndlrs/insthandler_test.go
  core/graphelier-service/api/hndlrs/msghandler_test.go
  core/graphelier-service/api/hndlrs/obhandler.go
  core/graphelier-service/api/hndlrs/obhandler_test.go
  core/graphelier-service/api/routes.go
  core/graphelier-service/db/mongo.go
  core/graphelier-service/models/orderbooks.go
  core/scripts/importer.py
  core/scripts/lobster/parser.py
  core/scripts/mongo_db/db_connector.py
Labels: refactor, time-dimension

#136 Set up prod for frontend #107
  README.md
  app/Dockerfile
  app/nginx/nginx.conf
  core/Dockerfile
  docker-compose.override.yml
  docker-compose.yml
Labels: web-hosting

#142 [#109] Set up CD pipeline to deploy on ECS
  .circleci/config.yml
Labels: CICD

#135 Safeguard BigInt in JS #104
  .gitignore
  app/.eslintrc.json
  app/package-lock.json
  app/package.json
  app/src/components/MessageList.js
  app/src/components/OrderBookSnapshot.js
  app/src/tests/utils/mock-data.js
  app/src/utils/date-utils.js
  package-lock.json
Labels: front-end, refactor

#143 [#109] Fixed URL issues
  .circleci/config.yml
  app/package.json
  app/src/constants/Constants.js
  core/Dockerfile
  docker-compose.override.yml
  docker-compose.yml
Labels: CICD

#140 Typescript migration
  app/.eslintrc.json
  app/package-lock.json
  app/package.json
  app/src/App.js
  app/src/App.tsx
  app/src/actions/actions.js
  app/src/actions/actions.ts
  app/src/actions/types.js
  app/src/actions/types.ts
  app/src/components/Home.tsx
  app/src/components/MessageList.tsx
  app/src/components/MultiDirectionalScroll.tsx
  app/src/components/NotFound.tsx
  app/src/components/Order.tsx
  app/src/components/OrderBookSnapshot.tsx
  app/src/components/PriceLevel.tsx
  app/src/components/TimestampOrderBookScroller.tsx
  app/src/components/template/Dashboard.tsx
  app/src/components/template/listItems.tsx
  app/src/constants/Constants.ts
  app/src/constants/Enums.ts
  app/src/env/serviceWorker.ts
  app/src/index.tsx
  app/src/models/OrderBook.ts
  app/src/react-app-env.d.ts
  app/src/reducers/generalReducers.ts
  app/src/reducers/reducers.js
  app/src/services/HttpClient.ts
  app/src/services/OrderBookService.js
  app/src/services/OrderBookService.ts
  app/src/setupTests.ts
  app/src/store/index.js
  app/src/store/index.ts
  app/src/styles/App.ts
  app/src/styles/Dashboard.ts
  app/src/styles/Home.ts
  app/src/styles/MessageList.ts
  app/src/styles/MultiDirectionalScroll.ts
  app/src/styles/NotFound.ts
  app/src/styles/Order.ts
  app/src/styles/OrderBookSnapshot.ts
  app/src/styles/PriceLevel.ts
  app/src/styles/TimestampOrderBookScroller.ts
  app/src/styles/WelcomeCard.js
  app/src/tests/App.test.tsx
  app/src/tests/component-tests/Dashboard.test.tsx
  app/src/tests/component-tests/MessageList.test.tsx
  app/src/tests/component-tests/MultiDirectionalScroll.test.tsx
  app/src/tests/component-tests/OrderBookSnapshot.test.tsx
  app/src/tests/component-tests/TimestampOrderBookScroller.test.js
  app/src/tests/component-tests/TimestampOrderBookScroller.test.tsx
  app/src/tests/utils/mock-data.ts
  app/src/utils/date-utils.ts
  app/src/utils/number-utils.ts
  app/src/utils/order-book-utils.ts
  app/tsconfig.json
Labels: front-end, refactor

#138 [#134] BDD tests using mamba for scripts
  .circleci/config.yml
  core/.gitignore
  core/scripts/importer.py
  core/scripts/lobster/extender.py
  core/scripts/lobster/extender.spec.py
  core/scripts/lobster/parser.spec.py
  core/scripts/models/message.py
  core/scripts/models/order_book.py
  core/scripts/models/order_book.spec.py
  core/scripts/pylintrc
  core/scripts/requirements.txt
  core/scripts/tests/messages_sample.fixture
  core/scripts/tests/test_extender.py
  core/scripts/utils/__init__.py
  core/scripts/utils/logger.py
Labels: documentation, test

#145 [#144] Fixed multiple ports being exposed
  README.md
  docker-compose.prod.yml
  docker-compose.yml
Labels: bug

#147 [#109] Fixed incorrectly named images in CI config
  .circleci/config.yml
Labels: bug

#149 [#148] Changed frontend to use elastic IP
  README.md
  app/src/constants/Constants.ts
Labels: CICD

#150 [#134] Utils, comments and refactoring for go test
  .circleci/config.yml
  core/graphelier-service/api/hndlrs/insthandler_test.go
  core/graphelier-service/api/hndlrs/msghandler_test.go
  core/graphelier-service/api/hndlrs/obhandler_test.go
  core/graphelier-service/mock_db/mock_mongo.go
  core/graphelier-service/models/orderbooks.go
  core/graphelier-service/models/orderbooks_test.go
  core/graphelier-service/utils/test_utils/common.go
  core/graphelier-service/utils/test_utils/httpreq.go
Labels: documentation, test

#151 [#146] Fixed crash on earliest time being selected
  app/src/components/MultiDirectionalScroll.tsx
Labels: bug, front-end

#153 [#134] Coverage reports for all components
  .circleci/config.yml
  core/.gitignore
Labels: CICD, test

#154 [#141] OrderInfo route added
  core/db/db_setup.js
  core/graphelier-service/api/hndlrs/orderhandler.go
  core/graphelier-service/api/hndlrs/orderhandler_test.go
  core/graphelier-service/api/routes.go
  core/graphelier-service/db/mongo.go
  core/graphelier-service/mock_db/mock_mongo.go
  core/graphelier-service/models/orderinfo.go
  core/graphelier-service/models/orderinfo_test.go
Labels: order-information

#152 [#134] Verbose logging with log levels for service
  core/graphelier-service/api/hndlrs/handlers.go
  core/graphelier-service/api/hndlrs/insthandler.go
  core/graphelier-service/api/hndlrs/msghandler.go
  core/graphelier-service/api/hndlrs/obhandler.go
  core/graphelier-service/db/mongo.go
  core/graphelier-service/main.go
  core/graphelier-service/utils/utils.go
Labels: enhancement

#159 [#123] Kontrolol/loading
  app/src/App.tsx
  app/src/components/CustomLoader.tsx
  app/src/components/GreetingsLoader.tsx
  app/src/components/MessageList.tsx
  app/src/components/OrderBookSnapshot.tsx
  app/src/components/TimestampOrderBookScroller.tsx
  app/src/constants/Constants.ts
  app/src/styles/App.ts
  app/src/styles/CustomLoader.ts
  app/src/styles/MessageList.ts
  app/src/styles/OrderBookSnapshot.ts
  app/src/styles/TimestampOrderBookScroller.ts
  app/src/styles/index.css
  app/src/tests/component-tests/MessageList.test.tsx
  app/src/tests/component-tests/OrderBookSnapshot.test.tsx
  app/src/tests/component-tests/TimestampOrderBookScroller.test.tsx
Labels: front-end, loading-icon, task

#161 [#132] Kontrolol/132/return to recent message
  app/src/components/MessageList.tsx
  app/src/components/MultiDirectionalScroll.tsx
  app/src/components/OrderBookSnapshot.tsx
  app/src/components/TimestampOrderBookScroller.tsx
  app/src/constants/Constants.ts
  app/src/styles/MessageList.ts
  app/src/tests/component-tests/MessageList.test.tsx
  app/src/tests/component-tests/TimestampOrderBookScroller.test.tsx
Labels: front-end, message-list, task

#160 #86 Top of book graph
  app/package-lock.json
  app/package.json
  app/src/components/MessageList.tsx
  app/src/components/OrderBookSnapshot.tsx
  app/src/components/TopOfBookGraph.tsx
  app/src/components/TopOfBookGraphWrapper.tsx
  app/src/constants/Constants.ts
  app/src/models/OrderBook.ts
  app/src/services/OrderBookService.ts
  app/src/styles/App.ts
  app/src/styles/OrderBookSnapshot.ts
  app/src/tests/component-tests/OrderBookSnapshot.test.tsx
  app/src/tests/utils/mock-data.ts
  app/src/utils/date-utils.ts
  core/db/db_setup.js
  core/graphelier-service/api/hndlrs/handlers.go
  core/graphelier-service/api/hndlrs/insthandler.go
  core/graphelier-service/api/hndlrs/msghandler.go
  core/graphelier-service/api/hndlrs/obhandler.go
  core/graphelier-service/api/hndlrs/orderhandler.go
  core/graphelier-service/api/hndlrs/topbookhandler.go
  core/graphelier-service/api/hndlrs/topbookhandler_test.go
  core/graphelier-service/api/routes.go
  core/graphelier-service/db/mongo.go
  core/graphelier-service/main.go
  core/graphelier-service/mock_db/mock_mongo.go
  core/graphelier-service/models/graph.go
  core/graphelier-service/models/orderbooks.go
  core/graphelier-service/utils/test_utils/httpreq.go
  core/scripts/importer.py
  core/scripts/mongo_db/db_connector.py
  core/scripts/mongo_db/db_utils.py
Labels: ToB-graph

#166 [#156] Added Milestone document
  CHANGELOG.md
  CourseAdmin/Graphelier Milestone2 Document.pdf
Labels: documentation

#167 [#164] Force interval_multiple to be an int64
  core/scripts/mongo_db/db_utils.py
Labels: bug, data

#168 [#156] Added missing scripts class diagram
  CourseAdmin/Graphelier Milestone2 Document - Revised Jan 29.pdf
  core/scripts/lobster/extender.py
Labels: documentation

#169 #123 Cleaned Code, improved performance.
  app/src/App.tsx
  app/src/components/GreetingsLoader.tsx
  app/src/styles/CustomLoader.ts
Labels: front-end, loading-icon, refactor
